language: python

python: "2.7"

sudo: false

# command to install dependencies
install:
  - easy_install -U pip
  - pip install PyYAML argparse
  - pip install catkin_pkg ros_buildfarm rosdistro nose coverage
  - pip install yamllint
  - pip install unidiff
  - pip install rosdep
  - pip install PyGithub

# command to run tests
script:
  - nosetests -s
  - yamllint */

notifications:
  email:
    on_success: never
    on_failure: always

branches:
  only:
    - master 

before_install: 
  - openssl aes-256-cbc -K $encrypted_ff7a3197787f_key -iv $encrypted_ff7a3197787f_iv -in .git-credentials.enc -out .git-credentials -d
